server:
  port: 9901
  servlet:
    context-path: /api/
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    threads:
      max: 800
      min-spare: 100

logging:
  level:
    com.sso: info
    org.springframework: warn
    root: info
  path: ${user.home}/logs/sso-auth-center

spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size:  10MB
      max-request-size:  20MB
  devtools:
    restart:
      enabled: true
  redis:
    host: 150.158.158.145
    port: 6379
    database: 0
    password: 123456
    timeout: 1000

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth-center?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456

sys:
  config:
    captchaType: math
    tokenHeader: Authorization
    tokenSecret: abcdefghijklmnopqrstuvwxyz
    tokenExpireTime: 180
    authSsoSysCode: auth-center
    supperAdminUser: 1000|admin
    ssoLoginUrl: http://www.myauth.com:9528/login
    fileProfile: ${user.home}/files/upload


aliyun:
  oss:
    file:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      keyid: 
      keysecret: 
      bucketname: authplatform
